### ISSUE TITLE
动态权限和路由

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#1]
有计划加入动态权限和路由吗？权限和路由都是从后台获取的。

**Comment by cloudhao1999** [comment]
感谢建议，我有空的时候看一下，后面应该会加上～

**Comment by cloudhao1999** [comment]
最新提交已添加动态权限与路由支持

**Comment by luoqiz** [comment]
我已经看了你的提交，但是和我做过的有些出入。
您可以看一下这个项目，看看这个项目的设计是否对您有帮助？
https://github.com/1942847253/yang-admin
