### ISSUE TITLE
建议： 加入 restful 风格的url地址访问

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#10]
![image](https://user-images.githubusercontent.com/22161059/181451262-eae6cc2e-b32a-4e70-ba25-96210980aca5.png)

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/181451262-eae6cc2e-b32a-4e70-ba25-96210980aca5.png)

最新版本中已支持，在useSimpleList中
