### ISSUE TITLE
bug： 表格位置错误

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#11]
当 表格的cloumns都没有 locked和showOverflowTooltip 属性的时候，表格位置靠右展示。

![image](https://user-images.githubusercontent.com/22161059/184297553-dc76507c-316a-4f82-9379-a0e40a3cfb7a.png)

**Comment by cloudhao1999** [comment]
> 当 表格的cloumns都没有 locked和showOverflowTooltip 属性的时候，表格位置靠右展示。
> 
> ![image](https://user-images.githubusercontent.com/22161059/184297553-dc76507c-316a-4f82-9379-a0e40a3cfb7a.png)

麻烦提供下columns的数据，我看看能不能复现

**Comment by cloudhao1999** [comment]
> 当 表格的cloumns都没有 locked和showOverflowTooltip 属性的时候，表格位置靠右展示。
> 
> ![image](https://user-images.githubusercontent.com/22161059/184297553-dc76507c-316a-4f82-9379-a0e40a3cfb7a.png)

之前我也有遇到类似的问题，所有column都设置了宽度就会这样，因为没有空余的列能自适应宽度

**Comment by cloudhao1999** [comment]
> 当 表格的cloumns都没有 locked和showOverflowTooltip 属性的时候，表格位置靠右展示。
> 
> ![image](https://user-images.githubusercontent.com/22161059/184297553-dc76507c-316a-4f82-9379-a0e40a3cfb7a.png)

最新版本已修复 287c7fcab8dabc52916ee5f98e4c242fb751c389

**Comment by luoqiz** [comment]
ok，测试正常
