### ISSUE TITLE
bug：表格滚动条错误

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#13]
表格列比较多的时候，同时将第一列和第二列固定的时候，下方滚动条使用错误。

**Comment by cloudhao1999** [comment]
> 表格列比较多的时候，同时将第一列和第二列固定的时候，下方滚动条使用错误。

没有很明白，能附图详细说明一下吗

**Comment by cloudhao1999** [comment]
我好像明白你的意思了，最新版本已修复你看看是不是解决了你的问题 9c356663640c007a74624739e92e31fa121642d9
