### ISSUE TITLE
Error: 打包报错

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#15]
![image](https://user-images.githubusercontent.com/22161059/185399254-4af8eedf-0559-4158-83a1-ac0e2a6190d8.png)

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/185399254-4af8eedf-0559-4158-83a1-ac0e2a6190d8.png)

我这边没有出现这个问题，可以重新安装下依赖再试试看

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/185399254-4af8eedf-0559-4158-83a1-ac0e2a6190d8.png)

应该是水印组件新引入的依赖，你重新安装下就好了

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/185399254-4af8eedf-0559-4158-83a1-ac0e2a6190d8.png)

6199bdc124d5628436f1af5eaaa20094e63dde8d
