### ISSUE TITLE
help: select 如何使用

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#17]
![image](https://user-images.githubusercontent.com/22161059/186115896-8d3547c1-dff8-4e93-ae6d-ba62936c5c7f.png)

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/186115896-8d3547c1-dff8-4e93-ae6d-ba62936c5c7f.png)

暂时还没有实现嵌套的功能，后续看能不能支持

**Comment by cloudhao1999** [comment]
最新版本看一下能不能解决你的问题，我写了一个在`design.ts`中，把注释去掉可以查看效果
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/32376445/186301895-65f1c093-c8f6-4ddc-bbce-553271212014.png">
option传入参数新增`children`属性，配置和option的一致，但是children不支持rules和children属性
<img width="898" alt="image" src="https://user-images.githubusercontent.com/32376445/186302552-6f624f43-f880-476f-9492-bd5612c50177.png">
核心逻辑在CForm.vue中，将children中的tagname传入内置组件component中渲染
<img width="794" alt="image" src="https://user-images.githubusercontent.com/32376445/186302641-d9f8c75f-10bf-4c5d-942d-d480bf594a06.png">
至于children中是否还有children，此类场景不是很常见就不去支持了，感兴趣的可以自己实现下

**Comment by luoqiz** [comment]
ok，我试一下
