### ISSUE TITLE
示例提供

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#18]
您提供的文章列表页面demo可展示的组件使用方式有点简单，我提供您两个json，您看看能否按照这个写一个各个组件的使用demo。

如有需要，我可以提供公网接口供您测试

第一个：租户管理的 json
{
    "code":200,
    "msg":"请求成功",
    "data":[
        {
            "id":"1",
            "name":"芋道源码",
            "contactUserId":null,
            "contactName":"芋艿",
            "contactMobile":"17321315478",
            "status":0,
            "domain":"https://www.iocoder.cn/",
            "packageId":"0",
            "expireTime":4075175656000,
            "accountCount":9999,
            "creator":"1",
            "createTime":1609837427000,
            "updater":"1",
            "updateTime":1645589711000,
            "deleted":false
        },
        {
            "id":"121",
            "name":"小租户",
            "contactUserId":"110",
            "contactName":"小王2",
            "contactMobile":"15601691300",
            "status":0,
            "domain":"http://www.iocoder.cn/",
            "packageId":"111",
            "expireTime":1710086400000,
            "accountCount":20,
            "creator":"1",
            "createTime":1645462574000,
            "updater":"1",
            "updateTime":1652753039000,
            "deleted":false
        },
        {
            "id":"122",
            "name":"测试租户",
            "contactUserId":"113",
            "contactName":"芋道",
            "contactMobile":"15601691300",
            "status":0,
            "domain":"https://www.iocoder.cn/",
            "packageId":"111",
            "expireTime":1651248000000,
            "accountCount":50,
            "creator":"1",
            "createTime":1646660278000,
            "updater":"1",
            "updateTime":1646660278000,
            "deleted":false
        }
    ],
    "total":"3",
    "pageIndex":1,
    "pageSize":10,
    "nextPageIndex":2
}

第二个 租户套餐管理json
{
    "code":200,
    "msg":"请求成功",
    "data":[
        {
            "id":"111",
            "name":"普通套餐",
            "status":0,
            "remark":"小功能",
            "menuIds":"[1024,1025,1,102,103,104,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023]",
            "creator":"1",
            "createTime":1645462440000,
            "updater":"1",
            "updateTime":1647686353000,
            "deleted":false
        }
    ],
    "total":"1",
    "pageIndex":1,
    "pageSize":10,
    "nextPageIndex":2
}

![image](https://user-images.githubusercontent.com/22161059/186117944-1f24249e-23d4-45d6-a558-97f9cc07f133.png)

![image](https://user-images.githubusercontent.com/22161059/186117880-add46202-660d-4def-baa7-09133d628e03.png)

**Comment by cloudhao1999** [comment]
感谢建议，后续看看有空完善一下～

**Comment by luoqiz** [comment]
基于这个两个json数据的基本页面构造我已经提交到我自己的项目里了，如有需要可以自取，
地址：  https://github.com/luoqiz/kite-admin-vue

**Comment by luoqiz** [comment]
在 dev 分支
