### ISSUE TITLE
建议使用 volta 来锁定 node、yarn 或 npm 的版本

### ISSUE THREAD

**Issue by Aurorxa** [cloudhao1999/cloud-app-admin#19]
https://docs.volta.sh/guide/

**Comment by cloudhao1999** [comment]
我对这个工具不是很了解🥸，看文档好像是对项目成员统一开发环境比较实用，感觉对这个项目的意义不是很大，因为下载的人并不一定想额外安装一个命令行工具，不过还是很感谢你的建议，也有可能是我自己理解错误哈，我会持续关注这个工具的～
