### ISSUE TITLE
请教运行问题

### ISSUE THREAD

**Issue by gdutyang** [cloudhao1999/cloud-app-admin#2]
作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下

**Comment by cloudhao1999** [comment]
> 作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下

可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题

**Comment by cloudhao1999** [comment]
> 作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下

我这边用Windows电脑+node12版本是跑不起来的，如果你的node版本是低于14建议升级成最新的长期支持版本16，这个项目用的技术比较新所以对于node版本要求会比较高一些

**Comment by gdutyang** [comment]
>>可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
>
>![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
我的node版本是 14.17.4 , npm的版本是 6.14.14

**Comment by gdutyang** [comment]
> > 作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> 
> 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题

![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454338-c49c722a-999c-4cf8-847e-5386152917ab.png)
![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454341-f7080299-efbe-4011-a6a4-d70e3b2f8fec.png)

**Comment by cloudhao1999** [comment]
> > > 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> > 
> > 
> > ![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
> > ![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
> > 我的node版本是 14.17.4 , npm的版本是 6.14.14

<img width="784" alt="image" src="https://user-images.githubusercontent.com/32376445/179457283-628c1abd-e9ff-4006-9475-d4219ec52f74.png">
官方的支持版本是14.18+，你的版本好像差了一点点，也许是版本的原因，你可以尝试升级node版本再试试看

**Comment by cloudhao1999** [comment]
> > > 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> > 
> > 
> > ![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
> > ![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
> > 我的node版本是 14.17.4 , npm的版本是 6.14.14

或者你可以试试在tags里面选择早期的分支，1.6以及以下的版本是vite2.0构建的，你可以试试旧版本的项目是否可以正常安装
<img width="507" alt="image" src="https://user-images.githubusercontent.com/32376445/179457669-9f485e29-4ac3-4d56-b6f1-19b30a669913.png">

**Comment by cloudhao1999** [comment]
> > > 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> > 
> > 
> > ![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
> > ![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
> > 我的node版本是 14.17.4 , npm的版本是 6.14.14
我找到了个和你类似的issue，看起来是node版本问题：https://github.com/UstymUkhman/vite-plugin-glsl/issues/15
他的解决方法是升级node版本到16，你可以试试，或者等待vite官方修复这个bug，或者尝试1.6以下的版本

**Comment by gdutyang** [comment]
> > > > 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> > > 
> > > 
> > > ![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
> > > ![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
> > > 我的node版本是 14.17.4 , npm的版本是 6.14.14
> 
> 或者你可以试试在tags里面选择早期的分支，1.6以及以下的版本是vite2.0构建的，你可以试试旧版本的项目是否可以正常安装 <img alt="image" width="507" src="https://user-images.githubusercontent.com/32376445/179457669-9f485e29-4ac3-4d56-b6f1-19b30a669913.png">

可以了，我把node升级到了16，感谢！

**Comment by cloudhao1999** [comment]
> > > > > 可以在issue里面把报错的截图贴出来，还有node版本和npm版本，vite3项目推荐的版本是node14以上，我是node16+pnpm的包管理器，node环境太老有可能出现跑不起来的问题作者你好 ！ 可以留一个联系方式吗？ 运行的时候报错了，没办法解决，想请教一下
> > > > 
> > > > 
> > > > ![QQ截图20220718141231](https://user-images.githubusercontent.com/79974139/179454175-37c23cb0-56f5-4251-897c-eb38c7a6be8f.png)
> > > > ![QQ截图20220718141250](https://user-images.githubusercontent.com/79974139/179454217-dc9ce40e-8b1b-44f1-9a3b-4738c7fa3591.png)
> > > > 我的node版本是 14.17.4 , npm的版本是 6.14.14
> > 
> > 
> > 或者你可以试试在tags里面选择早期的分支，1.6以及以下的版本是vite2.0构建的，你可以试试旧版本的项目是否可以正常安装 <img alt="image" width="507" src="https://user-images.githubusercontent.com/32376445/179457669-9f485e29-4ac3-4d56-b6f1-19b30a669913.png">
> 
> 可以了，我把node升级到了16，感谢！
嗯嗯行～那我把issue关闭了
