### ISSUE TITLE
error: 路由加入keepAlive: true后报错

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#21]
![image](https://user-images.githubusercontent.com/22161059/187075324-7130542e-3644-4f4e-bdae-762763fe4447.png)

**Comment by cloudhao1999** [comment]
请提供一下是哪个文件，如何复现～

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/187075324-7130542e-3644-4f4e-bdae-762763fe4447.png)

试试拉一下最新的代码看看，应该可以了

**Comment by cloudhao1999** [comment]
ec71c5f3d5df39fcefb6fe655a3d9f012f25b7d3

**Comment by cloudhao1999** [comment]
https://github.com/vuejs/core/issues/1865

**Comment by luoqiz** [comment]
标签在切换，但是页面内容没有变化，还有报错，报错内容也一样.

**Comment by luoqiz** [comment]
到公司后我测试一下，早上合并错项目了

**Comment by luoqiz** [comment]
验证成功
