### ISSUE TITLE
error： 打包错误

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#22]
执行的命令为： npm install n -g && n stable && npm install npm -g && npm install --force && npm run build
![image](https://user-images.githubusercontent.com/22161059/187175039-cef6d023-16df-4d7c-997d-3d5ad04dc481.png)

**Comment by cloudhao1999** [comment]
提供下node版本和npm的版本

**Comment by cloudhao1999** [comment]
https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by

**Comment by cloudhao1999** [comment]
看报错可能是node版本低，可以试着指定node版本到16以上再看看会不会报错

**Comment by luoqiz** [comment]
的确是node版本问题，升级node未启用最新版本
