### ISSUE TITLE
help：在Cfrom中添加富文本编辑器选项

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#23]
在cform中设置强制一行一个输入项，或者自适应多个。我的需求是：我一个表单大概有50个字段，弹出窗口小，而且一行放置了两个输入项，但是我好几个字段是富文本的，大多需要单独占一行，这个您看看怎么设置比较好。

**Comment by cloudhao1999** [comment]
> 在cform中设置强制一行一个输入项，或者自适应多个。我的需求是：我一个表单大概有50个字段，弹出窗口小，而且一行放置了两个输入项，但是我好几个字段是富文本的，大多需要单独占一行，这个您看看怎么设置比较好。

<img width="790" alt="image" src="https://user-images.githubusercontent.com/32376445/187444964-fbc88305-747d-4abc-8b53-00961084bdda.png">
可以针对每一项单独设置`colSpan`属性，一行是24，改成colSpan: { span: 24 }即可，colSpan中还可以配置其他参数，具体可查看Element Plus中的el-row组件的属性 

[Element Plus](https://element-plus.gitee.io/zh-CN/component/layout.html#col-%E5%B1%9E%E6%80%A7)
<img width="819" alt="image" src="https://user-images.githubusercontent.com/32376445/187445824-c0469812-dc4d-41c3-96f7-85e7f5a20745.png">

**Comment by cloudhao1999** [comment]
> 在cform中设置强制一行一个输入项，或者自适应多个。我的需求是：我一个表单大概有50个字段，弹出窗口小，而且一行放置了两个输入项，但是我好几个字段是富文本的，大多需要单独占一行，这个您看看怎么设置比较好。

<img width="1956" alt="image" src="https://user-images.githubusercontent.com/32376445/187447273-8df2a844-2853-494d-9315-bd048ca827f2.png">
<img width="1956" alt="image" src="https://user-images.githubusercontent.com/32376445/187447371-837f00b9-5ce3-4414-87da-baa6c95b50a8.png">
默认先读配置里的 colSpan

**Comment by luoqiz** [comment]
不是文本域，是富文本，我直接使用的WangEditor,整个表单都显示不了了

**Comment by cloudhao1999** [comment]
给个示例或者截图看一下

**Comment by cloudhao1999** [comment]
> 不是文本域，是富文本，我直接使用的WangEditor,整个表单都显示不了了

我大概明白你的意思了，可以按以下步骤试试看：
1.option中将tagName改成WangEditor的，colSpan设置一行
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/32376445/187584555-0f10e4b0-0e71-4fc2-b303-51208b8eef1b.png">
2.全局注册WangEditor
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/32376445/187584671-1ee1c4dc-8a74-4937-bfbd-dcc80c25f46f.png">
试试看能否解决你的问题
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/32376445/187585770-ddf6afcc-fa77-4511-88b9-b6f48b413c7b.png">

**Comment by cloudhao1999** [comment]
> 不是文本域，是富文本，我直接使用的WangEditor,整个表单都显示不了了

WangEditor需要全局注册一下才能在CForm中使用，autoImport不能针对component组件去识别，所以会出现不显示的问题
<img width="573" alt="image" src="https://user-images.githubusercontent.com/32376445/187585705-123f101e-c21d-4aa2-8bd3-670c85c6fde8.png">

**Comment by luoqiz** [comment]
嗯，我自己也调整好了，正打算提交pr呢。哈哈
