### ISSUE TITLE
建议： 封装图片上传到阿里云的组件

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#25]
以下代码是我以前封装的组件，您可以参考一下

https://github.com/luoqiz/kite-admin-antd-vue/blob/vite/src/components/ImageUpload/index.vue

**Comment by cloudhao1999** [comment]
最近可能没啥时间，我有空可以看一下，谢谢老哥建议～

**Comment by cloudhao1999** [comment]
阿里云的封装本项目可能不太会提供，组件的自身需求可以自行实现哈，谢谢支持
