### ISSUE TITLE
help: 页面内路由跳转

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#26]
需求： 单表字段特别多，只展示个别比较重要的字段所以分为多个操作按钮：
1：查看 按钮，跳转到一个新的窗口展示完整信息（根据id去后台查询完整信息）。
2：编辑 按钮，跳转到一个单开的路由页面。
3：新增 按钮，跳转到和编辑页面一样，携带空参数。

以上操作需要携带参数，如何携带参数跳转？
辛苦您写个例子吧。

**Comment by cloudhao1999** [comment]
按照上面的需求大致能理解为普通的crud，是有什么困难的点嘛，携带一个id到编辑页面调接口填充就好了，可能我没有太理解，可以再补充一下细节 edit的就/ArticleEdit?id=xxxx，新增就不传，查看/ArticleDetail?id=xxxx，页面载入时获取一下router的参数
