### ISSUE TITLE
TypeError: parentComponent.ctx.deactivate is not a function

### ISSUE THREAD

**Issue by midfar** [cloudhao1999/cloud-app-admin#27]
1. 从master分支拉代码
2. 修改 src/router/routes.ts 第14行，在meta中新增keepAlive属性，代码如下：
`meta: { menu: { title: "router.dashboard" }, keepAlive: true }`
3. npm run dev
4. 进入首页后，修改文件 src/views/HomePage.vue 第8行新增如下代码
`console.log('HomePage init')`
5. 触发热更新后，控制台报错：
Uncaught (in promise) TypeError: parentComponent.ctx.deactivate is not a function

**Comment by cloudhao1999** [comment]
> 1. 从master分支拉代码
> 2. 修改 src/router/routes.ts 第14行，在meta中新增keepAlive属性，代码如下：
>    `meta: { menu: { title: "router.dashboard" }, keepAlive: true }`
> 3. npm run dev
> 4. 进入首页后，修改文件 src/views/HomePage.vue 第8行新增如下代码
>    `console.log('HomePage init')`
> 5. 触发热更新后，控制台报错：
>    Uncaught (in promise) TypeError: parentComponent.ctx.deactivate is not a function

看了一下有人在vue的仓库也提到了这个问题，等待官方修复吧

**Comment by cloudhao1999** [comment]
https://github.com/vuejs/core/issues/6222
