### ISSUE TITLE
路由装载重复

### ISSUE THREAD

**Issue by fanhaoyang94** [cloudhao1999/cloud-app-admin#28]
您好，我在使用的过程中发现，刷新页面的时候组装路由的autoLoad方法会被调用两次
一次是初始化路由
一次是在路由守卫中
发现有token但是没有用户信息，则重新装载路由
不知道您是处于什么考虑，是因为权限么
因为，这种装载，远程路由接口会调用两次，而且，routes会出现重复的数据，希望大佬能解答我的疑虑

**Comment by cloudhao1999** [comment]
谢谢对本项目的支持，年代比较久远了，我翻出来看了看，如果你有下载本项目的话可以跑起来将 `guard.ts` 中 31 行关于 `autoload` 的代码注释掉，然后尝试在 `权限页面` 进行权限切换，当你将权限切换成 `editor` 后，你会发现本应该消失的 `额外权限` 菜单仍旧出现在页面中，所以 `autoLoad` 方法会被调用两次的原因正如你所言是为了使路由元数据能够匹配当前的角色，为什么不在 `autoload` 中判断呢，主要是为了方法的功能单一，所以将其放在路由守卫的逻辑中，至于您所说的重复数据我这边确实有发现，不过 `router` 似乎并不会展示重复的数据，页面上没有重复的菜单项，再次感谢你的支持，这个项目是我在学习 `Vue3` 期间的一个练习作品，我也不是啥大佬哈，如果您对于路由自动装载有更好的建议可以继续交流学习，也可以给我的项目提 `pr`，再次感谢 😆
