### ISSUE TITLE
登录故障

### ISSUE THREAD

**Issue by doudou-srp** [cloudhao1999/cloud-app-admin#29]
输入正确的邮箱或手机号，以及密码。登录校验报错。还有表单一输入就报警告啊
![image](https://github.com/cloudhao1999/cloud-app-admin/assets/64084394/ef8ee335-ac3a-4f76-b927-3ca85b166b26)
[Vue warn] Set operation on key "password" failed: target is readonly. Proxy(Object) {account: '', password: ''}

**Comment by cloudhao1999** [comment]
我在本机没有复现出您的 bug，请提供所使用的浏览器版本，操作系统，或者您可以使用其他浏览器再试试看
