### ISSUE TITLE
请教一下 slot radio checkbox  在 cForm.vue 中如何使用？

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#3]
![image](https://user-images.githubusercontent.com/22161059/180907124-3d2d416c-761f-4c22-9a36-0b35ba67a468.png)

**Comment by cloudhao1999** [comment]
> ![image](https://user-images.githubusercontent.com/22161059/180907124-3d2d416c-761f-4c22-9a36-0b35ba67a468.png)

最新的代码增加了补充示例，实现的思路是使用cForm扩充的scopeSlot字段，位置在ArticleEditDialog.vue，type字段中，可以看看能不能满足你的要求

**Comment by cloudhao1999** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/32376445/181154570-dcc32ecd-7718-4ed8-b1a9-25f7ae207df2.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/32376445/181154586-804a26b3-b48c-4914-8746-204a1ed2b49e.png">
