### ISSUE TITLE
useSimpleList 建议

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#4]
建议完善的方法分为 ： 新增、根据id删除、批量id删除、根据id的更新、查询。
同时写个简单使用示例。

**Comment by cloudhao1999** [comment]
> 建议完善的方法分为 ： 新增、根据id删除、批量id删除、根据id的更新、查询。 同时写个简单使用示例。

感谢建议，最新版本已添加，在文章列表的管理中实现
