### ISSUE TITLE
建议：标签栏控制

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#6]
添加标签栏的控制
![image](https://user-images.githubusercontent.com/22161059/181170873-d76e2c20-d36d-42a2-a99a-4a6caaf8dea3.png)

**Comment by cloudhao1999** [comment]
> 添加标签栏的控制 ![image](https://user-images.githubusercontent.com/22161059/181170873-d76e2c20-d36d-42a2-a99a-4a6caaf8dea3.png)

嗯嗯后续有时间可以加一下

**Comment by cloudhao1999** [comment]
> 添加标签栏的控制 ![image](https://user-images.githubusercontent.com/22161059/181170873-d76e2c20-d36d-42a2-a99a-4a6caaf8dea3.png)

最新代码已支持，感谢建议😀
