### ISSUE TITLE
建议： 表格控制

### ISSUE THREAD

**Issue by luoqiz** [cloudhao1999/cloud-app-admin#7]
表格控制（我公司的后台管理参考）

![image](https://user-images.githubusercontent.com/22161059/181171990-eaa847ab-379a-48c7-af99-c61615b470de.png)

**Comment by cloudhao1999** [comment]
> 表格控制（我公司的后台管理参考）
> 
> ![image](https://user-images.githubusercontent.com/22161059/181171990-eaa847ab-379a-48c7-af99-c61615b470de.png)

CTable的功能确实可以再完善一下，后续看看怎么做，感谢支持～

**Comment by cloudhao1999** [comment]
> 表格控制（我公司的后台管理参考）
> 
> ![image](https://user-images.githubusercontent.com/22161059/181171990-eaa847ab-379a-48c7-af99-c61615b470de.png)

你们公司是不是用的jeecg的后台模版，我看着好眼熟

**Comment by luoqiz** [comment]
不是  jeecg，  是vben框架。

**Comment by luoqiz** [comment]
我在网上看到一个后台，感觉他这个表格功能挺完善的，可以参考一下。
https://code.exmay.com/h5/pages/article/detail?id=1291

**Comment by cloudhao1999** [comment]
> 我在网上看到一个后台，感觉他这个表格功能挺完善的，可以参考一下。 https://code.exmay.com/h5/pages/article/detail?id=1291
嗯嗯感谢，目前已经实现了可选列和排序列，后续功能有空再完善一下～

**Comment by cloudhao1999** [comment]
后续的想法是把新增和批量删除的按钮逻辑也集成到table中，SearchFilter组件就只负责查询，后面再看看怎么优化
